const Menu = {
    menuList:[
        {
            name:'F工作台desk',
            className:'fa-home',
            key:1
        },
        {
            name:'财务管理',
            className:'fa-edit',
            childMenu:[
                {
                    name:'F账户管理',
                    url:'/financialcenter/financialmod/accountManage',
                    key:2
                },
                {
                    name:'F每日结算',
                    url:'/financialcenter/financialmod/settleMent',
                    key:3
                },
                {
                    name:'Demo',
                    url:'finance.html',
                    key:4
                },
                
            ]
        },
        {
            name:'资金管理',
            className:'fa-table',
            childMenu:[
                {
                    name:'F用户资金',
                    url:'/financialcenter/capitalmod/userCapital',
                    key:5
                },
                {
                    name:'F资金统计',
                    url:'/financialcenter/capitalmod/capitalCount',
                    key:6
                },
                {
                    name:'F账单明细',
                    url:'/financialcenter/capitalmod/billDetail',
                    key:7
                }
            ]
        },
        {
            name:'权限管理',
            className:'fa-desktop',
            childMenu:[
                {
                    name:'F角色权限',
                    url:'/systemcenter/authoritymod/functionRole',
                    key:8
                },
                {
                    name:'F功能管理',
                    url:'/systemcenter/authoritymod/functionManage',
                    key:9
                },
                {
                    name:'F操作员管理',
                    url:'/systemcenter/authoritymod/operManage',
                    key:10
                }
            ]
        },
        {
            name:'用户管理',
            className:'fa-sitemap',
            childMenu:[
                {
                    name:'F用户信息',
                    url:'/systemcenter/usermod/userInfo',
                    key:1-5-1
                },
                {
                    name:'F登录信息',
                    url:'/systemcenter/usermod/loginInfo',
                    key:1-5-2
                },
                {
                    name:'F认证信息',
                    url:'/systemcenter/usermod/identificationInfo',
                    key:1-5-3
                }
            ]
        },
        {
            name:'VIP管理',
            className:'fa-sitemap',
            childMenu:[
                {
                    name:'F积分规则',
                    url:'/systemcenter/vipmod/integralRule',
                    key:1-5-1
                },
                {
                    name:'F积分等级规则',
                    url:'/systemcenter/vipmod/integralVipRule',
                    key:1-5-2
                },
                {
                    name:'F积分流水',
                    url:'/systemcenter/vipmod/intergralBill',
                    key:1-5-3
                },
                {
                    name:'F用户等级',
                    url:'/systemcenter/vipmod/userVip',
                    key:1-5-3
                }
            ]
        },
        {
            name:'审核管理',
            className:'fa-sitemap',
            childMenu:[
                {
                    name:'F实名认证',
                    url:'/systemcenter/verifymod/identityAuthentication',
                    key:1-5-1
                },
                {
                    name:'FGoogle审核',
                    url:'/systemcenter/verifymod/googleVerify',
                    key:1-5-2
                },
                {
                    name:'F手机审核',
                    url:'/systemcenter/verifymod/phoneVerify',
                    key:1-5-3
                }
            ]
        },
        {
            name:'充提管理',
            className:'fa-sitemap',
            childMenu:[
                {
                    name:'F充值记录',
                    url:'/systemcenter/paymentMod/rechargeRecord',
                    key:1-5-1
                },
                {
                    name:'F充值地址',
                    url:'/systemcenter/paymentMod/rechargeAddress',
                    key:1-5-2
                },
                {
                    name:'F提现审核',
                    url:'/systemcenter/paymentMod/withdrawApprove',
                    key:1-5-3
                },
                {
                    name:'F提现地址',
                    url:'/systemcenter/paymentMod/withdrawAddress',
                    key:1-5-3
                },
                {
                    name:'F提现查询',
                    url:'/systemcenter/paymentMod/withdrawRecord',
                    key:1-5-3
                }
            ]
        }
    ]
};

export default Menu;




