// projectFakeData: [],//项目统计
//tradeFakeData: [],//交易区
//amountFakeData: [],//金额统计
//userFlowFakeData: [],//流量区

import { PIE_CHARTS,LINE_CHARTS,FUNNEL_CHARTS,BAR_CHARTS,LIST_TABLE,MAP_CHARTS,PIE_IMG_SRC,
    LINE_IMG_SRC,
    FUNNEL_IMG_SRC,
    BAR_IMG_SRC,
    LIST_IMG_SRC,
    MAP_IMG_SRC } from '../static/static'

import {
    TRADE_ENGINE,
    TRADE_HANDICAP_DEAL,
    TRADE_HANDICAP_DEAL_DSIT,
    TRADE_NEW_OLD_USER_EXCHANGE,
    TRADE_RANKING,
    TRADE_TATE_TOTAL,
    TRADE_TREND,
    TRADE_USER_EXCHANGE_MONEY,

    AMOUNT_DEPOSIT_MONEY,
    AMOUNT_EXCHANGE_MONEY_DIST,
    AMOUNT_HAND_FEE_CHANGE_TREND,
    AMOUNT_HAND_FEE_HANDICAP,
    AMOUNT_MONEY_FLOW_TREND,
    AMOUNT_PLATFORM_MONEY_DIST,
    AMOUNT_PRESERV_MONEY_DIST,
    AMOUNT_WALLET_CURRENCY_DIST,
    AMOUNT_WALLET_MONEY_DIST,
    AMOUNT_USER_MONEY_DIST,

    USER_ACTIVE_FORM,
    USER_CHINA_INTERVIEW,
    USER_EXCHANGE_NUM_RANKING,
    USER_GAIN_RANKING,
    USER_GLOBAL_INTERVIEW,
    USER_INTERVIEW_FLOW_TREND,
    USER_NEWUSER_TOTAL,

    EMPLOYER_DEPOSIT_PROP,
    EMPLOYER_EXCHAGNE_PROP,
    EMPLOYER_EXCHANGE_FREQ_TREND,
    EMPLOYER_EXCHANGE_NUM_TREND,
    EMPLOYER_HAND_FEE_DEVOTE,
    EMPLOYER_REGISTER,
    EMPLOYER_TO_PLATFORM_USER,
    EMPLOYER_TO_X_USER,
    EMPLOYER_WITHDRAW_PROP,
} from '../static/actionType'

export const tradeFakeData = [
    {
        img: FUNNEL_IMG_SRC,
        title: TRADE_TATE_TOTAL, //'交易转化率统计',
        description: '用户浏览、交易及交易转化率相关统计',
        key: 1,
        chartsType:FUNNEL_CHARTS,
        isShowTitle:true,
        tagTitle: 'TRADE_TATE_TOTAL'
    },
    {
        img: BAR_IMG_SRC,
        title: TRADE_HANDICAP_DEAL, //'盘口成交统计',
        description: '各个盘口交易量统计',
        key: 2,
        chartsType:BAR_CHARTS,
        isShowTitle:true,
        tagTitle: 'TRADE_HANDICAP_DEAL'
    },
    {
        img: PIE_IMG_SRC,
        title: TRADE_HANDICAP_DEAL_DSIT, //'盘口成交分布统计',
        description: '各个盘口交易量分布统计',
        key: 3,
        chartsType:PIE_CHARTS,
        isShowTitle:true,
        tagTitle: 'TRADE_HANDICAP_DEAL_DSIT'
    },
    {
        img: PIE_IMG_SRC,
        title: TRADE_NEW_OLD_USER_EXCHANGE, //'新老客户交易构成',
        description: '新老客户交易构成分布相关统计',
        key: 4,
        chartsType:PIE_CHARTS,
        isShowTitle:true,
        tagTitle: 'TRADE_NEW_OLD_USER_EXCHANGE',
    },
    {
        img: BAR_IMG_SRC,
        title: TRADE_USER_EXCHANGE_MONEY, //'用户交易金额统计',
        description: '用户交易金额区间范围的分布统计',
        key: 5,
        chartsType:BAR_CHARTS,
        isShowTitle:true,
        tagTitle: 'TRADE_USER_EXCHANGE_MONEY',
    },
    {
        img: LINE_IMG_SRC,
        title: TRADE_TREND, //'交易趋势',
        description: '交易币量与交易金额趋势统计',
        key: 6,
        chartsType:LINE_CHARTS,
        isShowTitle:true,
        tagTitle: 'TRADE_TREND',
    },
    // {
    //     img: BAR_IMG_SRC,
    //     title: TRADE_ENGINE, //'交易终端统计',
    //     description: '各个终端交易金额分布统计',
    //     key: 7,
    //     chartsType:BAR_CHARTS,
    //     isShowTitle:true,
    //     tagTitle: 'TRADE_ENGINE',
    // },
    {
        img: LIST_IMG_SRC,
        title: TRADE_RANKING, //'平台排行统计',
        description: '实时统计本交易所排名情况',
        key: 8,
        chartsType:LIST_TABLE,
        isShowTitle:true,
        tagTitle: 'TRADE_RANKING',
    },

]

export const amountFakeData = [
    {
        img: PIE_IMG_SRC,
        title: AMOUNT_EXCHANGE_MONEY_DIST, //'交易所金额分布',
        description: '交易所金额分布统计，统计内容：用户资金、平台账户、保值资金。',
        key: 1,
        chartsType:PIE_CHARTS,
        isShowTitle:true,
        tagTitle: 'AMOUNT_EXCHANGE_MONEY_DIST',
    },
    {
        img: PIE_IMG_SRC,
        title: AMOUNT_PLATFORM_MONEY_DIST, //'平台账户资金分布',
        description: '交易所账户资金分布，统计内容：交易手续费、提现手续费、原始运营资金。',
        key: 2,
        chartsType:PIE_CHARTS,
        isShowTitle:true,
        tagTitle: 'AMOUNT_PLATFORM_MONEY_DIST',
    },
    {
        img: PIE_IMG_SRC,
        title: AMOUNT_WALLET_MONEY_DIST, //'钱包资金分布',
        description: '交易所钱包资金分布，统计内容：交易手续费、提现手续费、原始运营资金。',
        key: 3,
        chartsType:PIE_CHARTS,
        isShowTitle:true,
        tagTitle: 'AMOUNT_WALLET_MONEY_DIST',
    },
    {
        img: PIE_IMG_SRC,
        title: AMOUNT_USER_MONEY_DIST, //'用户货币分布',
        description: '统计当前用户账户上的货币分布',
        key: 4,
        chartsType:PIE_CHARTS,
        isShowTitle:true,
        tagTitle: 'AMOUNT_USER_MONEY_DIST',
    },
    {
        img: PIE_IMG_SRC,
        title: AMOUNT_WALLET_CURRENCY_DIST, //'钱包货币分布',
        description: '统计当前钱包货币分布',
        key: 5,
        chartsType:PIE_CHARTS,
        isShowTitle:true,
        tagTitle: 'AMOUNT_WALLET_CURRENCY_DIST',
    },
    {
        img: PIE_IMG_SRC,
        title: AMOUNT_PRESERV_MONEY_DIST, //'保值资金分布',
        description: '当前保值平台资金分布统计',
        key: 6,
        chartsType:PIE_CHARTS,
        isShowTitle:true,
        tagTitle: 'AMOUNT_PRESERV_MONEY_DIST',
    },
    {
        img: LINE_IMG_SRC,
        title: AMOUNT_MONEY_FLOW_TREND, //'资金流动趋势',
        description: '"充值"、“提现”的趋势统计',
        key: 7,
        chartsType:LINE_CHARTS,
        isShowTitle:true,
        tagTitle: 'AMOUNT_MONEY_FLOW_TREND',
    },
    {
        img: PIE_IMG_SRC,
        title: AMOUNT_HAND_FEE_HANDICAP, //'手续费盘口统计',
        description: '按盘口统计手续费比例',
        key: 8,
        chartsType:PIE_CHARTS,
        isShowTitle:true,
        tagTitle: 'AMOUNT_HAND_FEE_HANDICAP',
    },
    {
        img: LINE_IMG_SRC,
        title: AMOUNT_HAND_FEE_CHANGE_TREND, //'手续费收取趋势',
        description: '统计手续费收入趋势',
        key: 9,
        chartsType:LINE_CHARTS,
        isShowTitle:true,
        tagTitle: 'AMOUNT_HAND_FEE_CHANGE_TREND',
    },
    {
        img:BAR_IMG_SRC ,
        title: AMOUNT_DEPOSIT_MONEY, //'沉淀资金',
        description: '沉淀资金',
        key: 10,
        chartsType:BAR_CHARTS,
        isShowTitle:true,
        tagTitle: 'AMOUNT_DEPOSIT_MONEY',
    },

]

export const userFlowFakeData = [
    {
        img: BAR_IMG_SRC,
        title: USER_ACTIVE_FORM, //'活跃用户构成',
        description: '交易所金额分布统计，统计内容：用户资金、平台账户、保值资金。',
        key: 1,
        chartsType:BAR_CHARTS,
        isShowTitle:true,
        tagTitle: 'USER_ACTIVE_FORM',
    },
    {
        img: LINE_IMG_SRC,
        title: USER_NEWUSER_TOTAL, //'新增用户统计',
        description: '交易所账户资金分布，统计内容：交易手续费、提现手续费、原始运营资金。',
        key: 2,
        chartsType:LINE_CHARTS,
        isShowTitle:true,
        tagTitle: 'USER_NEWUSER_TOTAL',
    },
    {
        img: LINE_IMG_SRC,
        title: USER_INTERVIEW_FLOW_TREND, //'访问流量趋势',
        description: '交易所钱包资金分布，统计内容：交易手续费、提现手续费、原始运营资金。',
        key: 3,
        chartsType:LINE_CHARTS,
        isShowTitle:true,
        tagTitle: 'USER_INTERVIEW_FLOW_TREND',
    },
    {
        img: LIST_IMG_SRC,
        title: USER_EXCHANGE_NUM_RANKING, //'用户交易量排行',
        description: '统计当前用户账户上的货币分布',
        key: 4,
        chartsType:LIST_TABLE,
        isShowTitle:true,
        tagTitle: 'USER_EXCHANGE_NUM_RANKING',
    },
    {
        img:MAP_IMG_SRC ,
        title: USER_CHINA_INTERVIEW, //'国内用户访问分布',
        description: '统计当前钱包货币分布',
        key: 5,
        chartsType:MAP_CHARTS,
        isShowTitle:true,
        tagTitle: 'USER_CHINA_INTERVIEW',
    },
    {
        img: MAP_IMG_SRC,
        title: USER_GLOBAL_INTERVIEW, //'全球用户访问分布',
        description: '当前保值平台资金分布统计',
        key: 6,
        chartsType:MAP_CHARTS,
        isShowTitle:true,
        tagTitle: 'USER_GLOBAL_INTERVIEW',
    },
    // {
    //     img:LIST_IMG_SRC ,
    //     title: USER_GAIN_RANKING, //'用户盈利排行',
    //     description: '"充值"、“提现”的趋势统计',
    //     key: 7,
    //     chartsType:LIST_TABLE,
    //     isShowTitle:true,
    // },
]

export const employerFakeData = [
    {
        img: LINE_IMG_SRC,
        title: EMPLOYER_REGISTER, //'资方用户注册',
        description: '交易所金额分布统计，统计内容：用户资金、平台账户、保值资金。',
        key: 1,
        chartsType:LINE_CHARTS,
        isShowTitle:true,
        tagTitle: 'EMPLOYER_REGISTER',
    },
    {
        img: PIE_IMG_SRC,
        title: EMPLOYER_EXCHAGNE_PROP, //'资方用户交易占比',
        description: '交易所账户资金分布，统计内容：交易手续费、提现手续费、原始运营资金。',
        key: 2,
        chartsType:PIE_CHARTS,
        isShowTitle:true,
        tagTitle: 'EMPLOYER_EXCHAGNE_PROP',
    },
    {
        img: LINE_IMG_SRC,
        title: EMPLOYER_EXCHANGE_NUM_TREND ,//'资方用户交易量趋势',
        description: '交易所钱包资金分布，统计内容：交易手续费、提现手续费、原始运营资金。',
        key: 3,
        chartsType:LINE_CHARTS,
        isShowTitle:true,
        tagTitle: 'EMPLOYER_EXCHANGE_NUM_TREND',
    },
    {
        img: LINE_IMG_SRC,
        title: EMPLOYER_EXCHANGE_FREQ_TREND, //'资方用户交易频率趋势',
        description: '统计当前用户账户上的货币分布',
        key: 4,
        chartsType:LINE_CHARTS,
        isShowTitle:true,
        tagTitle: 'EMPLOYER_EXCHANGE_FREQ_TREND',
    },
    {
        img:PIE_IMG_SRC ,
        title: EMPLOYER_WITHDRAW_PROP, //'资方用户提现占比统计',
        description: '统计当前钱包货币分布',
        key: 5,
        chartsType:PIE_CHARTS,
        isShowTitle:true,
        tagTitle: 'EMPLOYER_WITHDRAW_PROP',
    },
    {
        img:LINE_IMG_SRC ,
        title: EMPLOYER_DEPOSIT_PROP, //'资方用户存入与抛售统计',
        description: '当前保值平台资金分布统计',
        key: 6,
        chartsType:LINE_CHARTS,
        isShowTitle:true,
        tagTitle: 'EMPLOYER_DEPOSIT_PROP',
    },
    {
        img:PIE_IMG_SRC ,
        title: EMPLOYER_TO_PLATFORM_USER, //'转为平台用户统计',
        description: '"充值"、“提现”的趋势统计',
        key: 7,
        chartsType:PIE_CHARTS,
        isShowTitle:true,
        tagTitle: 'EMPLOYER_TO_PLATFORM_USER',
    },
    {
        img: PIE_IMG_SRC,
        title: EMPLOYER_TO_X_USER ,//'转为X用户统计',
        description: '按盘口统计手续费比例',
        key: 8,
        chartsType:PIE_CHARTS,
        isShowTitle:true,
        tagTitle: 'EMPLOYER_TO_X_USER',
    },
    {
        img: BAR_IMG_SRC,
        title: EMPLOYER_HAND_FEE_DEVOTE, //'资方用户手续费贡献统计',
        description: '统计手续费收入趋势',
        key: 9,
        chartsType:BAR_CHARTS,
        isShowTitle:true,
        tagTitle: 'EMPLOYER_HAND_FEE_DEVOTE',
    },

]
export const ONE = '1';
export const TWO = '2';
export const THREE = '3';
export const FOUR = '4';

