export default {
    // footer的国际化###################################################################################################
    "服务条款":"Terms of Use",
    "手续费":"Fees",
    "免责声明":"Disclaimer",
    "帮助中心":"Support Center",
    "商务":"Business Affairs: ",
    "客服":"Customer Service: ",
    // modal的国际化###################################################################################################
    "出错啦！您访问的网页不存在。": "No Found ! The requested document was not found",
    "访问首页": "Home Page",
    "取消":"Cancel",
    "确定":"Yes",
    "去登录":"Log in",
    // header###################################################################################################
    "币币交易":"Exchange",
    "多屏看板":"Spectaculars",
    "法币交易":"OTC",
    "新闻":"News",
    "公告":"Announcements",
    "订单":"Orders",
    "广告管理":"Offers",
    "资产管理":"Balances",
    "我的钱包":"My Wallet",
    "交易账户":"Trading Account",
    "用户中心":"Account",
    "资产折算":"Estimated Value",
    "退出登录":"Logout",
    "登录":"Login",
    "注册":"Sign Up",
    "阿波罗计划":"Apollo Program",
    "USD": "USD",
    "CNY": "CNY",
    "EUR": "EUR",
    "GBP": "GBP",
    "AUD": "AUD",
    //advertisement##############################################################################################
    "广告详情":"Offer Details",
    "下架":"Unpublish",
    "隐藏":"Hide",
    "上架":"Publish",
    "交易数量":"Amount",
    "交易金额":"Total Price",
    "订单状态":"Status",
    "订单编号：":"Order No：",
    "交易时间：":"Time：",
    "买家：":"Buyer：",
    "查看详情":"Details",
    "暂无订单信息":"No records",
    "说明：":"Tips:",
    "费率说明":"About Fees",
    "购买":"Buy",
    "出售":"Sell",
    "币种":"Coin",
    "市场":"Market",
    "固定单价":"Price",
    "交易总价":"Total Price",
    "单笔限额":"Single Limit",
    "请输入固定单价":"Enter fixed price",
    "请输入购买数量":"Please enter amount for buying.",
    "请输入出售数量":"Please enter the amount.",
    "账户余额：":"Account Balances：",
    "购买数量":"Amount",
    "出售数量":"Selling Amount",
    "最小限额（一次交易的最低交易限制）":"Min Limit",
    "最大限额（一次交易的最低交易限制）":"Max Limit",
    "付款方式":"Payment Methods",
    "资金密码":"Transaction Password",
    "总手续费":"Fee",
    "预计到账量":"Estimated Receive Amount",
    "温馨提示：":"Tips:",
    "实际冻结量":"Freezing amount",
    "暂无广告信息":"No records",
    "请输入资金密码":"Please enter transaction password.",
    "1.单笔限额中“最小限额”不低于当前交易币种最小交易量，“最大限额”不高于交易币种的挂单总数；":'1.The "Min Limit" of single order shall not be less than the minimum trading amount of the coin, and the "Max Limit" shall not be higher than total amount of the order placed',
    "2.购买广告手续费将从您购买的货币中扣除；":"2.The trade fee will be deducted from your buying.",
    "3.交易过程中，不要透露与您账户安全有关的敏感资讯":"3. Do not disclose sensitive information related to the security of your account during trading;",
    "4.请勿在 XX尝试欺诈行为，违者将会导致帐号被冻结，并承担法律责任。":"4.Do not attempt to commit frauds on platform. Violators will have their accounts frozen and will be held liable.",
    "2.售卖广告发布成功后，平台会锁定广告出售的货币数量和所需总手续费，当广告下架时会将未出售的货币和剩余手续费解除锁定。":"2.Once the sell offers published, platform will lock the total amount and the total fees required for offers. Unsold coins and remaining fees will be unlocked when offers are unpublished.",
    "4.交易过程中，请先确认款项入账后再释放数字货币。":"4.Please confirm the receipt of the payment before releasing the coins during transactions.。",
    "5.请勿在 XX尝试欺诈行为，违者将会导致帐号被冻结，并承担法律责任。":"5.Do not attempt to commit frauds on platform. Violators will have their accounts frozen and will be held liable.",
    "币种：":"Coin：",
    "类型：":"类型：",
    "广告类型：":"Type:",
    "广告类型":"Type",
    "数量":"Amount",
    "单价":"Price",
    "限额":"Limits",
    "已成交数量":"Filled Amount",
    "广告状态":"Status",
    "操作":"Action",
    "广告编号：":"No.",
    "创建时间：":"Creation Time：",
    "暂无广告信息":"No records",
    "输入广告编号":"Enter offer number",
    "全部":"All",
    "已上架":"Published",
    "已隐藏":"Hidden",
    "已下架":"Unpublished",
    "发布广告":"Post Offers",
    "输入订单号":"Enter order number",
    "您没有发布广告权限，请先认证商家身份":"You are not able to post offers, please verify the identity of merchant first",
 //order##############################################################################################
    "订单列表":"Orders",
    "交易类型：":"Trade type：",
    "交易类型":"Type",
    "日期：":"Date：",
    "交易币种":"Coin",
    "代付款":"Unpaid",
    "付款金额":"Total Price",
    "实际到账":"Receive Amount",
    "交易时间":"Order Time",
    "我的备注：":"My remarks:",
    "卖家：":"Seller：",
     //order新增
     "全部订单":'All',
     "订单编号":"No.",
     "待付款{num}":"Unpaid{num}",
     "待放币{num}":"Unreleased{num}",
     "交易完成{num}":"Completed{num}",
     "异常/申诉{num}":"Disputed{num}",
     "没有相关的订单记录":"No records",
     "交易完成":"Completed",
     "待放币":"Unreleased",
     "请选择日期":"Please select",
     "已下单":"Placed",
     "待付款":"Unpaid",
     "待释放货币":"Unreleased",
     "已下单，等待买家付款":"Ordered. waiting for buyer payment",
     "买家已付款，等待卖家释放货币":"buyer paid, waiting for seller to release currency",
     "卖家信息":"Seller Information",
     "买家信息":"Buyer Information",
     "备注：":"Notes:",
     "收款方式":"Payment Methods",
     "收款人":"Receiver",
     "开户行":"Bank",
     "开户支行":"Branch",
     "银行卡号":"Bank Account",
     "确认释放{coin}":"Confirm to release {coin}",
     "支付宝号":"Alipay",
     "收款码":"QR Code",
     "取消交易":"Cancel",
     "如果您已向卖家付款，为保护自身利益不要取消交易":"If you have paid to the seller, do not cancel the order.",
     "我确认没有付款":"Confirm I have not paid.",
     "付款确认":"Confirm Payment",
     "1.一单标记已付款，订单不可取消。":"1.Once marked “Paid”, the order cannot be cancelled.",
     "2.请勿在未付款的情况下点击“已付款”按钮，该行为属于恶意点击，当此类订单发生申诉时，系统将冻结买方平台账户。":"2.Do not click the “Paid” button in the case of non-payment, which is a malicious action. When such orders are complained, system will freeze the buyer's account.",
     "建议您输入转账时间和转账方式便于卖家账单核对，快速释放货币。":"You are advised to enter the transfer time and method for seller to check billing and release coins quickly.",
     "我确认已付款":"Confirm I have paid",
     "放弃申诉":"Give up",
     "放弃申诉_title":"Give up",
     "如果取消申诉，系统会直接判决对方获胜，请您慎重决定":"Once you cancelled the complaint, system will directly judge the other side won. Please think it carefully.",
     "我确认要放弃申诉":"Confirm to give up",
     "交易剩余时间：":"The remaining time:",
     "逾期将自动取消，请及时付款并点击":'Overdue trading will be cancelled automatically. Please pay in time and click',
     "我已付款":'"I have paid"',
     "我已付款_btn":'I have paid',
     "按钮":"button",
     "取消订单":"Cancel",
     "提醒买家":"Remind Buyer",
     "提醒卖家":"Remind Seller",
     "请等待对方付款，未收到付款不可释放货币":"Please wait for the payment by buyer, and don't release coins until you received it.",
     "请等待对方付款，未收到付款不可释放":"Please wait for the payment by buyer, and don't release {icon} until you received it",
     "释放":"Release",
     "释放{coin}":"Release xx",
     "交易信息":"Trade Information",
     "申述详情":"Details",
     "当前订单状态：":"Order status：",
     "订单详情":"Order Details",
     "分":':',
     "秒":' ',
     "未上传":"Not upload",
      "无效订单":"Invalid order",
      "对方已主动放弃申诉":"Other side dropped the complaint",
      "鼠标移入查看":"Move mouse to view",
      "收款金额":"Payment Amount",
      '(您必须用实名为：{name} 的账户向以下账户转账)':'( You must transfer money to the following account with your real name: {name})',
      '广告商备注':'Merchant Notes',
      '重置资金密码': 'Reset Transaction Password',
  //trade##############################################################################################
    "法币账户可用余额":"Fiat available balance",
    "成交笔数":"Trading History ",
    "我已收到款项":"I have received",
    "1.交易发起后，请您于交易截止前转账到卖家账户，并点击“我已付款”按钮，逾期系统将自动取消。":"1. Once you place an order, please timely pay to the seller's designated account and click the “Paid” button. System will cancel the trade automatically after the payment window expires.",
    "2. 交易发起后，系统会自动将卖家的数字货币锁定，待卖家确认收到您的转帐后，将会释放数字货币至您的账户中。":"2. When a trade is started, the coins will be automatically reserved from the seller's wallet by system. After the seller confirms your payment, it will be released to your account.",
    "3. 交易过程请使用平台的聊天系统进行沟通，平台外的对话记录将无法作为交易纠纷的依据。":"3.Please message the seller on platform for all communication during the trade. Message history outside platform may not be valid in the dispute.",
    "4. 超过三笔取消订单，将被冻结当天下单权限。":"4.You will be temporarily blocked from placing an order on the day you cancel more than three orders.",
    "法币：":"Fiat：",
    "商家":"Merchants",
    "交易":"Trade",
    "手续费：":"Fees：",
    "暂无交易信息":"No records",
    "收款设置":"Default Accounts",
    "去设置":"Set",
    "请设置收款方式":"Please set the payment methods",
    "请设置昵称、手机号、资金密码。":"Please set up nickname, phone number and transaction password.",
    "去认证":"Authenticate",
    "为了您的资金安全，进行交易前请完成身份认证":"For the security of your funds, please complete the identity authentication before trading!",
    "支付方式":"Payment Method",
    "支付方式：":"Payment:",
    "支付宝":"Alipay",
    "银行卡":"Bank Account",
    "已认证":"Authenticated",
    "未认证":"Unauthenticated",
    "注册时间":"Registration time",
    "首次访问法币时间":"First visit to OTC",
    "总订单数":"Total Orders",
    "平均放行时间":"Avg. Release Time",
    "%%日订单笔数":"Orders in %%days",
    "%%日完成率":"%%d Completion Rate",
    "移入黑名单":"Blacklist",
    "温馨提示：移入黑名单的用户将无法看到彼此的广告。并且将无法与您私信":"Warm reminder: Users in blacklist will not be able to see each other's offers or chat with you",
    "此用户付款方式为“银行卡”，请设置并开启“银行卡”":"This user's payment method is \"Bank Account\", please set and enable \"Bank Account\"",
    "此用户付款方式为“支付宝”，请设置并开启“支付宝”":"This user's payment method is \"Alipay\", please set and enable \"Alipay\"",
    "去开启":"Open",
    //representations##############################################################################################
    "申诉详情":"Details",
    "申诉详情：":"Details：",
    "未申诉":"Disputed",
    "申诉中":"In Complaint",
    "已完成":"Completed",
    "异常订单":"Disputed",
    "交易取消":"Cancelled",
    "申诉中":"In Complaint",
    "待释放货币":"Unreleased",
    "浏览器暂不支持":"Invalid browser",
    "暂无申诉":"No records",
    "忘记资金密码？":"Forgot your password?",
    "请输入申诉说明":"Enter complaint description",
    "订单状态：":"Order Status：",
    "申诉状态：":"Complaint Status：",
    "申诉说明":"Description",
    "申诉说明：":"Description：",
    "申诉截图：":"Sscreenshots：",
    "申诉视频：":"Video：",
    "提交申诉":"Submit",
    "补充申诉（N）":"Supplement (N)",
     "最多XXX张":"Up to XXX",
     "最多XXX组":"Up to XXX",
     "付款时间":"Time",
    "至少上传一张申诉截图":"Upload at least one screenshot of complaint",
    "至少上传一组申诉视频":"至少上传一组申诉视频",
    "申诉说明最多可输入200个符号":"The complaint description contains a maximum of 200 characters",
    "买方胜":"Buyer won",
    "卖方胜":"Seller won",
    "买方放弃申诉":"Buyer gave up",
    "卖方放弃申诉":"Seller gave up",
    "下载视频":"Download the video",
    "请及时提交申诉资料。":" Please  submit  complaint  information  in  time.",
    "请及时补充申诉资料。":"Please  supplement  complaint  information  in  time.",
    "请买家补充真实有效的付款证明图片。":"Please  add  real  and  valid  pictures  of  payment  proof.",
    "请买家补充清晰的付款信息的视频。":" Please  add  video  with  clear  payment  information.",
    "请买家补充相关聊天记录的截图或视频。": "Please  add  screenshots  of  relevant  chat  records  or  video.",
    "请卖家补充相关聊天记录的截图或视频。": "Please  add  screenshots  of  relevant  chat  records  or  video.",
    "请卖家补充清晰的未收到款项的视频。":  "Please  add  clear  video  of  the  payment  not  received.",
    "请卖家补充已释放货币的截图。":"Please  add  screenshot  of  the  released  coins.",
    //buyOrSellAdvertisement##############################################################################################
   "出售货币":"Sell Coins",
   "购买货币":"Buy Coins",
   "请输入最小限额":"Please enter Min Limit",
   "请输入最大限额":"Please enter Max Limit",
   "请输入单价金额":"Please enter price",
   "1.平台会对广告主收取每笔成交金额的{rate}作为手续费": "1.It will be charged {rate} from finished amount of whom posted the offer",
   "2.广告有效期为{days}天": "2.The validity period of offers is{days}days",
   "最大限额（一次交易的最高交易限制）":"Max Limit",
   "广告备注":"Offer Remarks",
   "可发布数量":"Number of posts",
   "广告备注将显示在广告详情中，请谨慎填写":"Offer remarks will be shown in the offer details. Please fill in carefully",
   "情况一：当法币账户余额 ≥（保证金*80% - 在途广告数量）":"Situation 1: when fiat account balance ≥ (deposit *80% - amount of pending offers)",
   "可发布数量=保证金*80% - 在途广告数量":" Number of posts = deposit *80% - amount of pending offers",
   "情况二：当法币账户余额 <（保证金*80% - 在途广告数量）":"Situation 2: when fiat account balance < (deposit *80% - amount of pending offers) ",
   "可发布数量=法币账户余额":"Number of posts = fiat account balance",
   //advertiseDetails##############################################################################################
   "隐藏确认":"Hidden Confirmation",
   "确认要进行广告隐藏吗？":"	Are you sure to hide the offer?",
   "下架确认":"Unpublished Confirmation",
   "广告一旦下架将不可复原，您确认要下架广告吗？":"Once unpublished the offer, it cannot be restored. Are you sure to insist?",
    "无效广告":"Invalid offer",
   //buySell##############################################################################################
   "%%分钟":"%% minutes",
   "立即出售":"Sell",
   "立即购买":"Buy",
   "下单金额应该在{num1}CNY到{num2}CNY之间":"The order amount should be between {num1}CNY and {num2}CNY",

   "单笔交易不能高于该广告的剩余数量。":"单笔交易不能高于该广告的剩余数量。",
   //rateStatement##############################################################################################
   "明白了，继续发布广告":"Got it, keep posting",
   "在转账过程中请勿备注{value}等信息，防止造成您的汇款被拦截、银行卡被冻结等问题，因此到账延迟，卖方可选择拒绝成交。":"在转账过程中请勿备注{value}等信息，防止造成您的汇款被拦截、银行卡被冻结等问题，因此到账延迟，卖方可选择拒绝成交。",
   "规定的时间内未达成交易，您可将问题进行申诉，我们会尽快协调双方进行最终交易":"You can lodge a complaint about the failed deal within stipulated time. We will coordinate to make the final deal ASAP",
   "申诉":"Complain",

    //在线聊天##############################################################################################
    "在线聊天":"Chat",
    "输入信息，回车发送":"Enter information and hit enter",
    "发送":"Send",
    "订单已创建，等待买家付款":"Order placed,waiting for buyer to pay",
    "请等待对方付款，未收到付款不可释放BTC":"Please wait for the payment by buyer, and don't release BTC until you received it",
    "请及时付款并点击我已付款按钮":'Please pay in time and click "I have paid" button',
    "买家已标记付款完成，请确保收到款项以后再释放货币":"Buyer has marked the completion of payment. Please make sure to release coins after receiving the payment",
    "交易成功":"Success",
    "交易成功，卖家已释放货币，请核对到账金额":"Success. Seller has released the coins. Please check the amount",
    "交易取消":"Cancelled",
    "买家已取消交易":"Buyer has cancelled the order ",
    "订单超时，系统自动取消":"Timeout. System has cancelled the order automatically",
    "订单异常":"Disputed",
    "对方已经进行申诉，为避免资金损失，请您尽快提交资料进行申诉":"The other side has lodged a complaint. In order to avoid loss, please submit your materials ASAP",
    "对方已提交申诉。":"The other side has lodged a complaint",
    "客服介入":"In Intervention",
    "客服介入，需补充材料。":"Customer service has intervened. Please supplement your materials",
    "材料已补充":"Supplemented",
    "对方已补充材料。":"There other side has supplemented materials ",
    "对方已补充申诉材料，请尽快查看":"The other side has supplemented materials for the complaint. Please check soon",
    "申诉成功":"Success",
    "平台综合资料判定买家胜诉":"Platform determined that the buyer won due to comprehensive information",
    "平台综合资料判定卖家胜诉":"Platform determined that the seller won due to comprehensive information",
    "申诉失败":"Failed",
    "您已将对方拉入黑名单，消息发送失败":"Failed to send the message since you have blacklisted the other side",
    "由于对方设置，你无法与TA对话":"You cannot chat with the other side because of his settings",
    "订单成功":"Success",
    //global tips##############################################################################################
    "您有新订单，请处理。":"You have a new order, please deal with it",
    "订单成功，您购买的BTC已到账。":"Success. The BTC you bought has arrived",
    "订单成功，您购买的VDS已到账。":"Success. The VDS you bought has arrived",
    "订单成功，您购买的USDT已到账。":"Success. The USDT you bought has arrived",
    "您有异常订单，请处理。":"You have a disputed order, please deal with it",
    "您有申诉订单，请处理。":"You have a order in complaint, please deal with it",

    "您有申诉订单需补充材料，请处理。":"You have a order in complaint to be supplemented, please deal with it.",
    "对方已支付，请处理。":"The other side has paid, please deal with it.",
    "下载视频":"Donwload",
   "返回":"Back",
   "申诉结果":"Result",
   "判定说明":"Statement",
   "您已获胜":"You won",
   "对方获胜":"Other side won",

    //upload##############################################################################################
    "上传凭证":"Upload",
    "大小不可超过30M":"Size shall not exceed 30M",
    "只支持主流视格式文件":"Only support mainstream video format files",
    "申诉截图大小不可超过5M":"The size of the complaint screenshots shall not exceed 5M",
    "只支持bmp、jpg、png和jpeg格式":"Only support .bmp .jpg .png and .jpeg formats",

    //
    "昵称": "nickname",
    "请设置": "Please set ",
    "手机号": "phone number ",
    "身份认证": "identity authentication",
    "在开始交易前，需要完善必要的交易信息，您还有{userInfo}未进行设置。请在{userCenter}进行设置。": "Before starting the trade, it is necessary to complete the transaction information. You have not set the {userInfo}. Please set it up in {userCenter}",
    "余额不足？去划转": "Insufficient balance？Transfer",
    "请设置xxx": "Please set up xxx",
    "超出可购买数量": "Exceeded the amount available",
    "至少选择一种支付方式": "Choose at least one payment method",
    "移除黑名单": "Unban",
    "广告编号": "Offer No.",
    "创建时间": "Creation Time",
    "已扣除手续费": "Deducted ",
    "剩余数量": "Available",
    "购买xxx": "Buy xxx",
    "出售xxx": "Sell xxx",
    "订单数量x笔": "x Orders",
    "订单数量": "Orders:",
    "x笔": "x",
    "绑定手机号": "phone number",
    "身份认证失败，请重新进行认证": "Identity authentication failed, please try again",
    "身份认证审核中，请稍后再试": "Identity authentication is in process, please try later",
    "广告已失效": "The offer has expired",
    "暂无更多广告": "No more offers",
    "您未设置收款方式": "You have not set the payment methods",
    "前往设置": "Set",
    "下架原因：": "Unpublished reason:",
    "隐藏原因：": "Hidden reason:",
    "您的广告数量已不足": "Your offer amount is insufficient ",
    "您的可交易数量已小于设置的最小限额": "Your tradable amount is less than the Min Limit set",
    "广告已超有效期": "Offer has expired",
    "您当日的取消订单的次数已达到N次，T小时后，广告会重新上架": "You have cancelled the orders N times a day that the offer will be republished after T hours",
    "您已主动下架广告": "You have initiatively unpublished the offer",
    "您已主动隐藏广告": "You have initiatively hidden the offer",
    "您今日取消订单次数已达N次，24小时内购买功能不可使用": "You have cancelled the orders N times today that you cannot carry out the buying within 24 hours",
    "不能交易自己创建的广告": "Unable to trade with the offers created by your own",
    "您有未处理完的订单交易": "You have pending orders",

    // 商家
    "当前价格": "Last Price",
    "24小时成交量": "24h Volume",
    "24小时最高价": "24h High",
    "24小时最低价": "24h Low",
    "申请广告商家认证": "Application for Merchant Certification",
    "广告商家享有0手续费及更多交易特权": "Merchants enjoy zero transaction fee and more privileges",
    "商家标识": "Merchant logo",
    "专属标识，增强交易方信任": "Exclusive logo, enhance trust on trading",
    "优先推荐": "Keep priority in recommend",
    "高效匹配，提高交易成单效率": "Efficient matching, improve trading efficiency",
    "专属客服": "Dedicated customer service",
    "7*24小时，一对一在线服务": "7*24 hours, one-to-one online service",
    "我已阅读并同意xxx": "I have read and agree to the xxx",
    "《广告商协议》": "Merchants Agreement",
    "立即认证": "Certificate",
    "今日数据": "Today's data",
    "进行中的订单(x)": "进行中的订单(x)",
    "异常/申诉订单(x)": "异常/申诉订单(x)",
    "近期订单(x)": "近期订单(x)",
    "24小时内": "24小时内",
    "3天内": "3天内",
    "一周内": "一周内",
    "类型": "类型",
    "状态": "状态",
    "交易对象": "交易对象",
    "实名": "实名",
    "总价": "总价",
    "货币": "货币",
    "下单时间": "下单时间",
    "操作时限": "操作时限",
    
    // 商家
    "当前价格": "Last Price",
    "24小时成交量": "24h Volume",
    "24小时最高价": "24h High",
    "24小时最低价": "24h Low",
    "申请广告商家认证": "Application for Merchant Certification",
    "广告商家享有0手续费及更多交易特权": "Merchants enjoy zero transaction fee and more privileges",
    "商家标识": "Merchant logo",
    "专属标识，增强交易方信任": "Exclusive logo, enhance trust on trading",
    "优先推荐": "Keep priority in recommend",
    "高效匹配，提高交易成单效率": "Efficient matching, improve trading efficiency",
    "专属客服": "Dedicated customer service",
    "7*24小时，一对一在线服务": "7*24 hours, one-to-one online service",
    "我已阅读并同意{xxx}": "I have read and agree to the {xxx}",
    "《广告商协议》": "Merchants Agreement",
    "立即认证": "Certificate",
    "今日数据": "Today's data",
    "进行中的订单(x)": "Pending Orders(x)",
    "异常/申诉订单(x)": "Disputed Orders(x)",
    "近期订单(x)": "Recent Orders(x)",
    "24小时内": "within 24h",
    "3天内": "within 3days",
    "一周内": "within 1week",
    "类型": "Type",
    "状态": "Status",
    "交易对象": "Trade Object",
    "实名": "Real-name",
    "总价": "Total Price",
    "货币": "Coin",
    "下单时间": "Trade Time",
    "操作时限": "Operation Timed",
    "缴纳保证金": "Deposit Payment",
    "取消认证": "Cancel",
    "继续认证": "Continue",
    "您法币账户中USDT余额为：xxx": "The USDT balance in your fiat account is: xxx",
    "您法币账户中USDT余额为：{xxx}": "The USDT balance in your fiat account is: {xxx}",
    "点击充值": "click Deposit",
    "已成交订单数": "Number of Filled Orders",
    "累计出售总额": "Total Selling Amount",
    "累计购买总额": "Total Buying Amount",
    "法币账户资产余额": "Balances for Fiat",
    "我已阅读并同意": "I have read and agree to the ",
    "认证中": "In Certification",
    "重新认证": "Re-Certificate",
    "十分抱歉，您的申请未审核通过，原因为：xxx": "Sorry, your application was not approved due to xxx",
    "提示：取消商家认证后，保证金会退还至法币账户余额中": "Tips: after the merchant certification is cancelled, the deposit will be returned to the fiat account",
    "您还未获得发布权限，请联系客服": " You are not able to post offers, please contact customer service",
    "请输入正确的资金密码": "Please enter correct transaction password",
    "保证金与可发布广告的总量相关联": "The deposit is related to the amount of posting offers",
    "前往认证": "Authenticate",
    "尚未实名认证": "Not authenticated",
    "请您先完成实名认证后，再申请广告商家认证": "Please complete the identity authentication first, then apply for merchant certification",
    "订单编号.": "Order No.",
    "超时": "Timeout",
    "标记已付款": "I hve paid",
    "确认并释放": "Comfirm and Release",
    "当前项无相关数据": "No data",
    "保证金金额不足": "Insufficient deposit",
    "商家认证": "Merchants Certification",
    "工作台": "Workbench",
    "您输入资金密码错误次数已达上限，请24小时候尝试": "Transaction password input error too many times in a row, please try again after 24 hours",
    "提交成功，请耐心等待审核": "Success, please wait patiently for review",
    "1.目前平台不收取任何手续费": "1.No fees required here at present",
    "理财中心": "Financing",
    "姓名": "Name",
    "订单限时": "Order Time-limit",
    "支付信息": "Payment Information",
    "商家认证审核中，请稍后再试": "Awaiting merchant verification, please try again later",

    //title 标签内容
    "默认首页":"Btcwinex-the world's most professional and secure digital asset service platform.Focus on trading BTC,VDS,VOLLAR,EOS,LTC,ETH and other digital currency.",
    "申请商家权限":"Apply for Merchant",
    "广告管理_1":"Offers",
    "我的订单":"My Orders",


}